### PR TITLE
Rename linear_RTO to linearRTO

### LINKED ISSUE #74: Change Linear_RTO to LinearRTO in CUQIpy-demos
After update in https://github.com/CUQI-DTU/CUQIpy/pull/284 we need to reflect this change in the training notebooks. It might only be exercise 04 that needs explicit update.

To use the latest change install CUQIpy via `pip install cuqipy --pre`

### PR DESCRIPTION
**Pull request by chaozg**
Closes #74

### CODE REVIEW

**Comment by jakobsj** [comment]
Wonderful, thank you @chaozg!  I wonder if this should be targeted at https://github.com/CUQI-DTU/CUQIpy-demos/tree/fix_66_update_exercise04_training_Sept_2023 instead of main -  or perhaps wait until that one is merged?

**Review by amal-ghamdi — COMMENTED** [review]
Thank you @chaozg  for the PR, Looks great! 😊 

I agree with @jakobsj to may be wait on merging until  #71 is merged. Just to avoid any conflict.

**Comment by nabriis** [comment]
LGTM :)

**Review by nabriis — APPROVED** [review]

**Review by amal-ghamdi — APPROVED** [review]
LGTM

**Pull request merged**
