### PR TITLE
Sprint20 demo update

### LINKED ISSUE #58: demo repo: CUQIpy-FEniCS example: update to reflect update in CUQIpy-FEniCS
The main updates are:

1- Change MaternExpansion to MaternKLExpansion 
2- Forward and Adjoint BC should be updated to reflect updates in the cuqipy_fenics library

### LINKED ISSUE #59: Training demos fail, needs removal of eg GaussianCov
This happens for example in Exercise01_Minimal_UQ.ipynb. GaussianCov, GaussianPrec. Also results look different (worse) than I remember but to double check.

### LINKED ISSUE #60: Make sure cuqipy-demos run with new release

### PR DESCRIPTION
**Pull request by amal-ghamdi**
closes #59 closes #58 closes #60 

Remaining issues to be addressed (for CIL and Ex01 demos): #63 #64 

I fixed the demos to reflect the updates in CUQIpy and its plug-ins, some additional notes:
- In Ex04, I changed the STD for the deconvolution prior from 0.1 to 0.5 (which improved the results)
- In the PyTorch demo, I updated the prior cov from 0.1 to 0.2 for the deconvolution problem. This made the exact solution be within the credible interval (but the reconstruction is not improved much).
- In the FEniCS demo I made some improvements, the original demo did not use the noisy data so I updated that, And I change the noise variance.

### CODE REVIEW

**Comment by amal-ghamdi** [comment]
@jakobsj and @nabriis, I appriacte if you can review this PR. There are outstanding issues for which I created two issues #63 and #64. Also please see my notes above in this PR description. Thanks!

**Review by jakobsj — APPROVED** [review]
Thank you for going through the demos so carefully and updating them, a somewhat tedious job but valuable outcome.  I looked through and everything looks good, so approving immediately.  If you want, you can show us some of the bigger changes and remaining bits left as separate issues when we meet tomorrow.

**Comment by amal-ghamdi** [comment]
Thank you @jakobsj for your review. I just realized, in a loosely related note, that we did not update the demo repo to require 2 reviewers. Should we do that?

**Review by nabriis — APPROVED** [review]
Looks good to me. I could not easily view some of the changes to the notebooks, but the ones I could see looked good.

**Comment by amal-ghamdi** [comment]
> Looks good to me. I could not easily view some of the changes to the notebooks, but the ones I could see looked good.

Thank you @nabriis !

**Pull request merged**
